version: "3.8"

services:
  springboot-app:
    build:
      context: ./Test_Backend_JAVA
      dockerfile: Dockerfile
    image: app-back
    container_name: backend
    ports:
      - "8095:8090"
    volumes:
      - ./src:/app/src
      - ./target:/app/target
    depends_on:
      mysql:
        condition: service_healthy

      frontend:
        condition: service_healthy  

    restart: always
    networks:
      - app_network

  mysql:
    image: mysql:latest
    container_name: mysql_database
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: codsoft-back
      MYSQL_USER: arwa
      MYSQL_PASSWORD: arwa
      MYSQL_ROOT_PASSWORD: rootpassword
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "--silent"]
      interval: 10s
      timeout: 5s
      retries: 5

  frontend:
    build:
      context: ./BookingForm_Frontend
      dockerfile: Dockerfile
    image: app-front
    container_name: frontend
    ports:
      - "91:80"
    networks:
      - app_network    

networks:
  app_network:
    driver: bridge
